outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
names(outcome)
heart30 <- as.numeric(outcome[,17])
pneum30 <- as.numeric(outcome[,23])
heartAttack30 <- as.numeric(outcome[,11])
par(mfrow = c(3,1))
hist(heartAttack30, main = "Heart Attack", xlab = "30-day Death Rate")
hist(heart30, main = "Heart Failure", xlab = "30-day Death Rate")
hist(pneum30, main = "Pneumonia", xlab = "30-day Death Rate")
par(mfcol = c(1,3))
ham <- mean(heartAttack30, na.rm=TRUE)
hm <- median(heart30, na.rm=TRUE)
pm <- median(pneum30, na.rm=TRUE)
hist(heartAttack30, main = "Heart Attack", xlab = "30-day Death Rate")
abline(v=ham)
hist(heart30, main = "Heart Failure", xlab = "30-day Death Rate")
abline(v=hm)
hist(pneum30, main = "Pneumonia", xlab = "30-day Death Rate")
abline(v=pm)
ham <- median(heartAttack30, na.rm=TRUE)
abline(v=ham)
hist(heartAttack30, main = paste("Heart Attack (X=", ham, ")", sep=""), xlab = "30-day Death Rate")
hist(heartAttack30, main = paste("Heart Attack (", tilde(X==ham), ")", sep=""), xlab = "30-day Death Rate")
